In [21]:
pip install -U scikit-learn

     ---------------------------------------- 0.0/60.6 kB ? eta -:--:--
     ------ --------------------------------- 10.2/60.6 kB ? eta -:--:--
     ------------ ------------------------- 20.5/60.6 kB 217.9 kB/s eta 0:00:01
     -------------------------------------- 60.6/60.6 kB 535.5 kB/s eta 0:00:00
  Using cached joblib-1.4.2-py3-none-any.whl.metadata (5.4 kB)
  Using cached threadpoolctl-3.5.0-py3-none-any.whl.metadata (13 kB)
   ---------------------------------------- 0.0/11.0 MB ? eta -:--:--
   - -------------------------------------- 0.5/11.0 MB 9.8 MB/s eta 0:00:02
   ---- ----------------------------------- 1.2/11.0 MB 12.3 MB/s eta 0:00:01
   ------- -------------------------------- 2.0/11.0 MB 12.8 MB/s eta 0:00:01
   ----------- ---------------------------- 3.1/11.0 MB 15.3 MB/s eta 0:00:01
   ----------------- ---------------------- 4.9/11.0 MB 17.3 MB/s eta 0:00:01
   --------------------- ------------------ 6.0/11.0 MB 17.5 MB/s eta 0:00:01
   -----------------------

In [88]:
pip freeze

anyio==4.4.0
argon2-cffi==23.1.0
argon2-cffi-bindings==21.2.0
arrow==1.3.0
asttokens==2.4.1
async-lru==2.0.4
attrs==23.2.0
Babel==2.15.0
beautifulsoup4==4.12.3
bleach==6.1.0
blinker==1.8.2
certifi==2024.6.2
cffi==1.16.0
charset-normalizer==3.3.2
click==8.1.7
colorama==0.4.6
comm==0.2.2
debugpy==1.8.1
decorator==5.1.1
defusedxml==0.7.1
exceptiongroup==1.2.1
executing==2.0.1
fastjsonschema==2.19.1
Flask==3.0.3
fqdn==1.5.1
greenlet==3.0.3
h11==0.14.0
httpcore==1.0.5
httpx==0.27.0
idna==3.7
importlib_metadata==7.1.0
ipykernel==6.29.4
ipython==8.18.1
isoduration==20.11.0
itsdangerous==2.2.0
jedi==0.19.1
Jinja2==3.1.4
joblib==1.4.2
json5==0.9.25
jsonpointer==2.4
jsonschema==4.22.0
jsonschema-specifications==2023.12.1
jupyter-events==0.10.0
jupyter-lsp==2.2.5
jupyter_client==8.6.2
jupyter_core==5.7.2
jupyter_server==2.14.1
jupyter_server_terminals==0.5.3
jupyterlab==4.2.1
jupyterlab_pygments==0.3.0
jupyterlab_server==2.27.2
MarkupSafe==2.1.5
matplotlib-inline==0.1.7
mistune==3.0.2
nbclient==0

In [2]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_csv(r"https://raw.githubusercontent.com/mwaskom/seaborn-data/master/mpg.csv")

In [6]:
df = df.drop("name", axis=1)

In [10]:
df.head()

mpg  cylinders  displacement  horsepower  weight  acceleration  \
0  18.0          8         307.0       130.0    3504          12.0   
1  15.0          8         350.0       165.0    3693          11.5   
2  18.0          8         318.0       150.0    3436          11.0   
3  16.0          8         304.0       150.0    3433          12.0   
4  17.0          8         302.0       140.0    3449          10.5   

   model_year origin  
0          70    usa  
1          70    usa  
2          70    usa  
3          70    usa  
4          70    usa

In [12]:
df.origin.value_counts()

origin
usa       249
japan      79
europe     70
Name: count, dtype: int64

In [13]:
def origin(x):
    if x == "usa":
        return 1
    else:
        return 0

In [14]:
df["origin"] = df.origin.apply(origin)

In [15]:
df.head()

mpg  cylinders  displacement  horsepower  weight  acceleration  \
0  18.0          8         307.0       130.0    3504          12.0   
1  15.0          8         350.0       165.0    3693          11.5   
2  18.0          8         318.0       150.0    3436          11.0   
3  16.0          8         304.0       150.0    3433          12.0   
4  17.0          8         302.0       140.0    3449          10.5   

   model_year  origin  
0          70       1  
1          70       1  
2          70       1  
3          70       1  
4          70       1

In [16]:
X = df.drop("mpg", axis=1)

In [17]:
y = df.mpg

In [52]:
from sklearn.preprocessing import MinMaxScaler
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import RandomizedSearchCV
from sklearn.pipeline import Pipeline

In [23]:
norm = MinMaxScaler()
norm.fit(X)
X_sc = norm.transform(X)

In [24]:
RandomizedSearchCV??

Init signature:
RandomizedSearchCV(
    estimator,
    param_distributions,
    *,
    n_iter=10,
    scoring=None,
    n_jobs=None,
    refit=True,
    cv=None,
    verbose=0,
    pre_dispatch='2*n_jobs',
    random_state=None,
    error_score=nan,
    return_train_score=False,
)
Source:        
class RandomizedSearchCV(BaseSearchCV):
    """Randomized search on hyper parameters.

    RandomizedSearchCV implements a "fit" and a "score" method.
    It also implements "score_samples", "predict", "predict_proba",
    "decision_function", "transform" and "inverse_transform" if they are
    implemented in the estimator used.

    The parameters of the estimator used to apply these methods are optimized
    by cross-validated search over parameter settings.

    In contrast to GridSearchCV, not all parameter values are tried out, but
    rather a fixed number of parameter settings is sampled from the specified
    distributions. The number of parameter settings that are tried is
    given b

In [26]:
params = {
    "max_depth": [3, 5, 7, 9],
    "n_estimators": [100, 200, 300]
}

# Initialize the RandomForestRegressor
rf = RandomForestRegressor(n_jobs=-1)

# Set up RandomizedSearchCV
grid = RandomizedSearchCV(
    estimator=rf,
    param_distributions=params,
    n_iter=10,  # Number of parameter settings that are sampled
    cv=5,  # Number of folds for cross-validation
    verbose=2,
    n_jobs=-1,
    random_state=42
)

grid.fit(X_sc, y)

Fitting 5 folds for each of 10 candidates, totalling 50 fits


RandomizedSearchCV(cv=5, estimator=RandomForestRegressor(n_jobs=-1), n_jobs=-1,
                   param_distributions={'max_depth': [3, 5, 7, 9],
                                        'n_estimators': [100, 200, 300]},
                   random_state=42, verbose=2)

In [54]:
pipe = Pipeline([
    ("norm", MinMaxScaler()),
    ("rf", RandomForestRegressor(n_jobs=-1))
])

# Define the parameter grid
params = {
    "rf__max_depth": [3, 5, 7, 9],
    "rf__n_estimators": [100, 200, 300]
}

# Set up RandomizedSearchCV
grid = RandomizedSearchCV(
    estimator=pipe,
    param_distributions=params,
    n_iter=10,  # Number of parameter settings that are sampled
    cv=5,  # Number of folds for cross-validation
    verbose=2,
    n_jobs=-1,
    random_state=42
)

# Fit the grid to the data
grid.fit(X, y)


Fitting 5 folds for each of 10 candidates, totalling 50 fits


RandomizedSearchCV(cv=5,
                   estimator=Pipeline(steps=[('norm', MinMaxScaler()),
                                             ('rf',
                                              RandomForestRegressor(n_jobs=-1))]),
                   n_jobs=-1,
                   param_distributions={'rf__max_depth': [3, 5, 7, 9],
                                        'rf__n_estimators': [100, 200, 300]},
                   random_state=42, verbose=2)

In [55]:
grid.best_estimator_.score

<bound method Pipeline.score of Pipeline(steps=[('norm', MinMaxScaler()),
                ('rf',
                 RandomForestRegressor(max_depth=9, n_estimators=200,
                                       n_jobs=-1))])>

In [56]:
grid.best_score_

0.754589694766868

In [57]:
import pickle
with open("model.plk", "wb") as f:
    pickle.dump(grid.best_estimator_, f)

In [58]:
with open("model.plk", "rb") as f:
    saved_model = pickle.load(f)

In [59]:
df.head()

mpg  cylinders  displacement  horsepower  weight  acceleration  \
0  18.0          8         307.0       130.0    3504          12.0   
1  15.0          8         350.0       165.0    3693          11.5   
2  18.0          8         318.0       150.0    3436          11.0   
3  16.0          8         304.0       150.0    3433          12.0   
4  17.0          8         302.0       140.0    3449          10.5   

   model_year  origin  
0          70       1  
1          70       1  
2          70       1  
3          70       1  
4          70       1

In [64]:
predict_df = pd.DataFrame(np.array([8,307, 190, 3504, 12, 70, 1]).reshape(1,-1), columns=X.columns)
predict_df

cylinders  displacement  horsepower  weight  acceleration  model_year  \
0          8           307         190    3504            12          70   

   origin  
0       1

In [66]:
y.head(1)

0    18.0
Name: mpg, dtype: float64

In [67]:
saved_model.predict(predict_df)

array([15.73920747])

In [68]:
dir(norm)

['__annotations__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__sklearn_clone__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_build_request_for_signature',
 '_check_feature_names',
 '_check_n_features',
 '_doc_link_module',
 '_doc_link_template',
 '_doc_link_url_param_generator',
 '_get_default_requests',
 '_get_doc_link',
 '_get_metadata_request',
 '_get_param_names',
 '_get_tags',
 '_more_tags',
 '_parameter_constraints',
 '_repr_html_',
 '_repr_html_inner',
 '_repr_mimebundle_',
 '_reset',
 '_sklearn_auto_wrap_output_keys',
 '_validate_data',
 '_validate_params',
 'clip',
 'copy',
 'data_max_',
 'data_min_',
 'data_range_',
 'feature_names_in_',
 'feature_range',
 '

1era opcion:

In [47]:
norm.data_max_

array([8.00e+00, 4.55e+02, 2.30e+02, 5.14e+03, 2.48e+01, 8.20e+01,
       1.00e+00])

In [48]:
norm.data_min_

array([   3.,   68.,   46., 1613.,    8.,   70.,    0.])

2nda opcion:

In [49]:
import pickle
with open("norm.plk", "wb") as f:
    pickle.dump(norm, f)

In [50]:
with open("norm.plk", "rb") as f:
    saved_norm = pickle.load(f)

In [51]:
saved_norm.transform(predict_df)

array([[-0.4       , -0.1741148 , -0.2475189 , -0.45717716, -0.46201814,
        -5.83333333,  1.        ]])

3era opcion

In [ ]:
Hacer un pipe, con la normalizacion y con el modelo directamente

In [71]:
from sqlalchemy import create_engine
import sqlite3

In [72]:
churro = "sqlite:///mpgdb.db"

In [73]:
engine = create_engine(churro)

In [77]:
from datetime import datetime

In [78]:
date = str(datetime.now())[0:19]

In [76]:
inputs = str(predict_df.values[0])

In [80]:
outputs = saved_model.predict(predict_df)[0]

In [83]:
log_df = pd.DataFrame({"inputs":[inputs], "outputs": [outputs], "date": [date]})

In [84]:
log_df.to_sql("logs", con=engine, if_exists="append", index= None)

1

In [87]:
pd.read_sql("SELECT * FROM logs", con= engine)

inputs    outputs  \
0           [   8  307  190 3504   12   70    1]  15.739207   
1  ['10', '400', '250', '4000', '15', '70', '1']  13.406280   

                  date  
0  2024-06-10 10:23:12  
1  2024-06-10 10:35:18

In [89]:
!pip install psycopg2-binary

   ---------------------------------------- 0.0/1.2 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.2 MB ? eta -:--:--
   -- ------------------------------------- 0.1/1.2 MB 812.7 kB/s eta 0:00:02
   ------------ --------------------------- 0.4/1.2 MB 3.2 MB/s eta 0:00:01
   ------------------------------------- -- 1.1/1.2 MB 7.0 MB/s eta 0:00:01
   ---------------------------------------- 1.2/1.2 MB 6.2 MB/s eta 0:00:00


In [98]:
import pandas as pd
from sqlalchemy import create_engine

In [103]:
churro = "postgresql://postgres:postgresql@34.34.169.17/postgres"

In [104]:
engine = create_engine(churro)

In [105]:
df = pd.DataFrame({"a": [1,2,3], "b":[4,5,6]})

In [106]:
df.to_sql("test", con=engine)

3

In [107]:
pd.read_sql("SELECT * FROM test", con=engine)

index  a  b
0      0  1  4
1      1  2  5
2      2  3  6

In [108]:
saved_model.predict(X)

array([17.10744909, 14.6856745 , 16.97888652, 16.34365217, 17.1305569 ,
       14.41586617, 14.01296335, 14.145677  , 13.27882789, 14.66094691,
       14.93173689, 14.64326383, 14.89587954, 14.63469672, 23.94328403,
       21.4081529 , 19.27349352, 20.98645147, 27.11314185, 26.68021627,
       24.08375471, 24.36800596, 24.47523289, 25.11601685, 20.85435988,
       10.61289946, 10.74454069, 11.49672013,  9.735     , 27.12001685,
       25.74166985, 25.19708217, 26.1014873 , 19.2048649 , 16.89167654,
       17.54530013, 18.4534558 , 18.21620133, 13.99951703, 13.53254545,
       14.07247936, 14.2913145 , 12.08701422, 12.84776073, 12.50151698,
       18.38833472, 21.89144506, 18.41476161, 18.2688537 , 23.96644622,
       26.811761  , 29.63294203, 28.79459271, 31.48114333, 33.42720989,
       27.76495267, 27.38097161, 24.77948949, 26.14564642, 24.00315972,
       20.64357035, 23.01702554, 13.70803985, 13.4552698 , 14.37353725,
       14.06143872, 15.64284296, 11.90837814, 12.7825505 , 12.71